### ISSUE TITLE
BUG: Ecoverses, created before COMMUNICATIONS_ENABLED was set to true, cannot send updates

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1442]
**Describe the bug**
Ecoverses, created before COMMUNICATIONS_ENABLED was set to true, cannot send updates

**To Reproduce**

1. Go to https://acc.alkem.io/admin/hubs/digicampus/community/updates as a global admin
2. Fill in the update markdown 
3. Click post
4. Nothing happens. There is an exception:
 **LOG Message: Unable to add user admin@alkem.io: already added?: TypeError: Cannot read property 'hasMembershipState' of null**

**Expected behavior**
1. Go to https://acc.alkem.io/admin/hubs/digicampus/community/updates as a global admin
2. Fill in the update markdown 
3. Click post
4. The update is successfully emitted. Update message can be visualized on the screen.

The correct behaviour can be observed sending updates on https://acc.alkem.io/admin/hubs/communicationshub/community/updates

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/3e4a7a3d-0ad4-46a2-997d-ea6928a3bab5)us/community/updates

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/17d4bcbd-a0d5-4888-b740-3390d2051ee3)

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/faee2e4c-91c9-4e81-a9c4-80c7617e0af3)
**Additional context**

**Comment by techsmyth** [comment]
This error message is triggered when the room cannot be located, so highly likely there was a room configured on the community but since then the homeserver db had been refreshed. https://github.com/alkem-io/server/pull/1450 ensures that the underlying error is now shown. 

Please check again to see if you can reproduce the error using that branch and with a clean alkemio db.

**Comment by Comoque1** [comment]
The issue seems to be resolved on DEV env.
