### ISSUE TITLE
BUG: unable to tag user

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2764]
**Describe the bug**
I am unable to tag the following user on production: https://alkem.io/user/karthik-mahadevan-1370

**To Reproduce**

1. Go to any forum or card commend, and start typing in `@kar...` - nothing shows up

**Expected behavior**
I am able to tag karthik!
API tests are updated to cover this functionality.

**Comment by techsmyth** [comment]
maybe his preference for being tagged is disabled? Consider showing such users as grayed out (not taggable)

Note: that preference is enabled:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/26bb374d-ce9b-4400-94ce-42abe8e41f64)

**Comment by techsmyth** [comment]
@Comoque1 can you please investigate this one?

**Comment by Comoque1** [comment]
@techsmyth, the issue is caused by the filtered email. After having a chat with @ccanos, it appears, that when mention user it uses `displayName` AND `email` and when the mail is different from displayName seaarch is failing to return results.

**Comment by ccanos** [comment]
we are calling `usersPaginated` > user.service.ts: `getPaginatedUsers`
and that is finding users by `profile.displayName` and then filtering them. I always thought that it was a OR filtering, turns out it's an AND, 
so it's returning only the users that have the search term in their email address.

We can quickly fix it making the client not send the email field. But also we can fix it making the function search with an OR on the other fields. that means changing `applyFiltering` a bit and it's used in a few more places (users and orgs)

**Comment by techsmyth** [comment]
@ccanos nice analysis - and glad it is found. Filtering by email is important so we do need that to be kept. The filtering is being done on the server right?

**Comment by techsmyth** [comment]
@ccanos @hero101 I would have thought also that the getPaginatedUsers is an OR filter. Svetlo: easy enough change?

**Comment by hero101** [comment]
Yes, it has been `OR` but changed due to the `displayName` being moved, so a special case just for the `displayName` had to be created.  Since the solution is generic I am unaware of the impact a simple switch like that would bring. The ideal case is the `displayName` check needs to be included in that bracket statement.
```sql
WHERE `profile`.`displayName` like ? AND (`user`.`email` LIKE ? OR `user`.`firstName` LIKE ?)
```

**Comment by techsmyth** [comment]
It should be all OR - so

```sql
WHERE `profile`.`displayName` like ? OR (`user`.`email` LIKE ? OR `user`.`firstName` LIKE ?)
```

**Comment by hero101** [comment]
Issue has been transferred to the server repo
