### ISSUE TITLE
BUG: Dev env is failing to start

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3313]
**Describe the bug**
Dev env is failing to start as the default space is being created without profile data.
The issue started being hit after all merges and a new alkemio database on dev env.

**To Reproduce**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjA4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc0fb932b225c97d97f7ffc65c7ba169876678d4/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm84QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84635e4df90bd04a0926f9b2e3e5015f574d479b/image.png)

**Expected behavior**
Dev env is loading successfully.

**Comment by hero101** [comment]
it seems to be due to the table definition being different than the entity and graphql definitions.
The definition in `calloutTemplate1693849043894` defines `whiteboardContent` as `NOT NULL` , but the definition in `CalloutContributionDefaults` and `ICalloutContributionDefaults` states `whiteboardContent` to be `nullable`.
This makes it acceptable for the `create` logic to try and create a record without the field.

**Comment by hero101** [comment]
Solved by making `whiteboardContent ` nullable.
Credits to @alstojanovic
