### ISSUE TITLE
Every time I sign in with LinkedIn I have to give permission

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#3429]
**Sorry, not sure in what repository this belongs**

**Describe the bug**
Every time I sign out (microsoft) and sign in with LinkedIn, I have to give permission again. This feels weird since on other platforms, I only have to give this permission once

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a92d47d242d45f0e0a0086cb6919d20222e2e5fc/image.png)

**Expected behavior**

Spike: 2 hours investigation

**Comment by valentinyanakiev** [comment]
@techsmyth fount it and again not on our side. If you go to your personal preferences, you have [data settings](https://www.linkedin.com/mypreferences/d/data-sharing-for-permitted-services). Remove your authorizations, re-authorize again. Sign out, sign in and you will be prompted to authorize. Sign out again and sign in (n amount of times) and you won't be prompted. I suspect this issue is related to metadata kept in Linkedin, I suspect it may be something like they changed the schema and something was missing so we kept being prompted. 

There is no remediation on our side, apart from me getting a new app so everybody is authorized once again - I suspect then the issue will go away...

**Comment by valentinyanakiev** [comment]
There is absolutely nothing wrong with our code and with Kratos, it seems like we meet the specs of the flow 100%.

**Comment by valentinyanakiev** [comment]
Raised an issue to create a new app https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/infrastructure-operations/1123
