### ISSUE TITLE
BUG: server crash on error in application

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3894]
**Describe the bug**

**To Reproduce**
1. Go to localhost:3000
2. Create a public space with public challenge
3. Using a non member user create application directly to the challenge
4. Using the admin of the challenge approve the application - the server crash
<img width="1816" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmZFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac89c439ffcda5685ad7a89c60a52a50b6ce3a66/image.png" alt="image.png" />

**Expected behavior**
User cannot apply on subspace, without being a member on parent.

**Comment by techsmyth** [comment]
@Comoque1 just tried this flow out. The client gave the appropriate message to first join the parent space - so that seems to be ok. I also tried going to the apply directly + then got the following page:
<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXpOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f19c80b04309f1d00a2a6013da449d661a58478f/image.png" alt="image.png" />

So something goes wrong in the client - low priority as users should not be able to get to this page. So please retest and if flow works for users then close...

**Comment by Comoque1** [comment]
@techsmyth , you are right, at the time of the issue has been raised, the flows on the client were broken, so now using the client, cannot be reproduce (at least not a direct flow).

Still, if for some reason, a user has or creates an application on a subspace, without being a space member , and someone approve it, the server crash (tested on dev env.).
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXY5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d72a16fb9b75c76e611af3530d3f782ca969cb45/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 this is an exception cascade issue, will need Svetlo to have look at this re why the error triggers a server crash...

**Comment by Comoque1** [comment]
Tested locally with latest changes and the server still crash. @hero101 , could you please have a look at the issue, when you have the time?

**Comment by techsmyth** [comment]
Closing this as it is the same issue as #4618
