### ISSUE TITLE
Spike: Convert project to ESM + type module

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4459]
## Description

As a developer I want to be able to use the latest packages

## Acceptance criteria

- [ ] Investigate what is needed for the server repository to be able to use latest ESM packages

## Additional Context
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@reactoholic can you please pick this up when you next come clear?

**Comment by reactoholic** [comment]
> @reactoholic can you please pick this up when you next come clear?

Absolutely! :)

**Comment by techsmyth** [comment]
@reactoholic let me know if this needs to be prioritized against other work; it is one that needs addressing

**Comment by reactoholic** [comment]
Good morning, @techsmyth 👋 I will take a look at it right after I finish Bobbi's PR review 🙂

**Comment by reactoholic** [comment]
Hello, @techsmyth 👋

I've done some research and a quick test locally regarding the ESM conversion. It boils down to these steps:
1. Simple refactor in the `package.json` file
2. Simple refactor in the `tsconfig.json` file
3. Convert every import statement in the entire server application to include the .js file extension explicitly. Example: 

From
```
import {
  GeoInformation,
  GeoLocationService,
} from '@services/external/geo-location';
```
to
```
import {
  GeoInformation,
  GeoLocationService,
} from './services/external/geo-location.js';
```

I could not identify an alternative method to convert our application to ESM. While the complexity of the process I found out about is minimal, the task is highly time-consuming due to the extensive number of files in the server application. Many of these files include 10 to 20 import statements, which complicates the update process. This manual update cannot be automated using the IDE's bulk search-and-replace functionality, and I estimate it would take approximately 2 to 3 days to complete—or potentially longer. Only after completing this step can we confirm if the application has been fully converted to ESM.

In addition, a comprehensive test of the application will be required post-conversion, which would take at least one full day to complete.

To mitigate risk and optimize our efforts, I propose creating a task for an ESM Proof of Concept (PoC). The goal would be to replicate the structure of our server application in a smaller project and apply the same conversion process. This approach would allow us to validate the method before committing to a full refactor of our main repository.

**Comment by techsmyth** [comment]
Thanks Petar, sounds doable. Also the core of it (updating the imports) sounds super manual - which I have to believe is automatable. It may need to be done outside of an IDE - e.g. use CoPilot or similar to create a script to find all import statements + for every one that does not end in .js' to add the .js piece. Suggest we chat through on Monday...and basically I think we need to do the conversion to find the real gotchas, which I suspect there will be...

**Comment by techsmyth** [comment]
@reactoholic please do continue on this stream, good to get any issues surfaced up. Btw, find it hard to understand why we would be importing a js file - that seems to go against the whole concept of Typescript...

**Comment by reactoholic** [comment]
> @reactoholic please do continue on this stream, good to get any issues surfaced up. Btw, find it hard to understand why we would be importing a js file - that seems to go against the whole concept of Typescript...

The issue isn't related to TypeScript but rather to how ESM operates. The process of importing files remains the same regardless of the file extension. Omitting the extension is merely syntactic sugar, whereas the explicit `.js` extension is a requirement for ESM to function properly—it simply won't export ESM modules without it.
