### ISSUE TITLE
BUG: Content visible

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#4524]
**Describe the bug**
In the search results, I see content (posts) from a subspace in a private Space
I also see Subspaces that are part of a private Space

**To Reproduce**
1. search for offsite (when you are not a member of the Building the A-team space)
2. See offsite subspace in a private space

or search for content

**Expected behavior**
I can't see any content from private spaces (subspaces, posts, etc.)

**Screenshots**

**Comment by techsmyth** [comment]
@valentinyanakiev @hero101 there needs to be an authorization check for READ access on this result type.

**Comment by techsmyth** [comment]
Notes after discussion:
<img width="956" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHRxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30416792dad06220a1c7a5cd2b3cee3f1d018b83/image.png" alt="image.png" />

Above is with a user that is not logged in. Note the lack of READ priviliege on the space entity. 

Subspace in question: 2ffa118a-981e-47c8-9828-8c941d54346c - is in a private space - so the not logged in user should not see it. Note also that the actual content of the subspace is protected, only the profile (display name etc) is available due to this bug.

**Comment by Comoque1** [comment]
Tested OK on ACC and PROD.
