### ISSUE TITLE
Show users with tags first + randomize

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#4545]
## Description

When I open the contributors page, I always see the same faces/initials

## Acceptance criteria

- [ ] Show people with **tags** first
- [ ] Randomize each time page loaded

## Additional Context
Actual need is to show people with avatars first, but since we can't "see" if people are using avatars, 'having tags'  is used instead. When people have tags, they'll probably also have an avatar.. 

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
Notes:
- only the users with tags are displayed, the others are not available;
- because of the above, the search is hidden for now;
@Comoque1 FYI

____
@SimoneZaza , we should revisit this page at some point (as agreed).
Having:
- less than the actual results;
- having randomized placement on every refresh;
It looks more like a negative than a positive UX.

**Comment by Comoque1** [comment]
Tested OK on ACC env with respect to the comments and AC.

Note:
organizations are not randomized.
