### ISSUE TITLE
BUG: Inviting user to a global role throws an error

### ISSUE THREAD

**Issue by DonnaDuiker** [cherrytwist/Server#4718]
**Describe the bug**
GraphQL code to invite a new user to the platform with role generates an error

**To Reproduce**

1. Go to alkem.io/graphql
2. Perform the following mutation:
```
mutation {
  inviteUserToPlatformWithRole(
    invitationData: {
      email: "comoque+1077@gmail.com"
      platformRole: VC_CAMPAIGN
      welcomeMessage: "test"
    }
  ) {
    id
  }
}
```
3. Error is thrown: `"message": "Field 'createdBy' doesn't have a default value",`
<img width="1789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0hMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c1985f394efbfca240015af9f93b4650321da99/image.png" alt="image.png" />

**Expected behavior**
I expect the e-mail adrress that I inserted in the code to be invited without an error.

**Comment by valentinyanakiev** [comment]
fixed in release/entitlements branch + merged to develop @Comoque1

**Comment by Comoque1** [comment]
Tested OK on DEV env. Still due to the issues around the entitlements, user cannot create entities, that he is supposed to after successful registration. After account reset - all is good. Raised separate [card](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/4723) about it.
